title: SMART BANKING
description: Сайт за умно банкиране

url: https://Smart-Banking.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

social:
  email: cxpucmob@gmail.com
#  github: brianmaierjr
#  linkedin: https://Smart-Banking.github.io

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Начало
    url: /index.html
  - title: За SMART BANKING
    url: /intro
  - title: Контакти
    url: /contact
  - title: Съдържание
    url: /contents

disqus:
  shortname: smart-banking
  # -github-io

remote_theme: brianmaierjr/long-haul
plugins:
- jekyll-remote-theme
